### ISSUE TITLE
[!] Xcodeproj doesn't know about the following attributes {"buildSettings"=>{}, "buildStyles"=>["DFFDE1CD5BAC4D7FB55EF000", "0C477B0EF93C4B059CE637BA", "E3881ACE651B4C59856D2FE7", "EE636A413BDA4D1D8E135344"]} for the 'PBXProject' isa.

### ISSUE THREAD

**Issue by yoferzhang** [CocoaPods/Xcodeproj#891]
[!] Xcodeproj doesn't know about the following attributes {"buildSettings"=>{}, "buildStyles"=>["DFFDE1CD5BAC4D7FB55EF000", "0C477B0EF93C4B059CE637BA", "E3881ACE651B4C59856D2FE7", "EE636A413BDA4D1D8E135344"]} for the 'PBXProject' isa.

**Comment by igor-makarov** [comment]
Hi @yoferzhang!

Unfortunately these Xcode project attributes are deprecated and have been deprecated for a long time now. The reason they are still appearing is because CMake is creating them.

Here's some more info on the subject: https://github.com/facebookarchive/xcbuild/issues/24 (issue from 2016).

There's a script someone made in the comments [here](https://github.com/CocoaPods/CocoaPods/issues/6325#issuecomment-365370771) that you might want to use to clean the project file.
