### ISSUE TITLE
Upgrade REXML to 3.3.2 or later

### ISSUE THREAD

**Issue by subhams087** [CocoaPods/Xcodeproj#952]
The REXML gem before 3.3.1 has some DoS vulnerabilities when it parses an XML that has many specific characters such as <, 0 and %>.  If you need to parse untrusted XMLs, you may be impacted to these vulnerabilities. The REXML gem 3.3.2 or later include the patches to fix these vulnerabilities.

**Comment by douglashill** [comment]
This was already addressed on `master` in https://github.com/CocoaPods/Xcodeproj/pull/948, although there hasn’t so far been a release including this change.

Note that are additional vulnerabilities fixed in REXML 3.3.3:

- https://github.com/ruby/rexml/security/advisories/GHSA-5866-49gr-22v4
- https://github.com/ruby/rexml/security/advisories/GHSA-r55c-59qm-vjw6

**Comment by paulb777** [comment]
Duplicate of #947
